# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GoogleDrive\3D\Python\education\09_projManager\homework_projectManager\uis\projectManager.ui'
#
# Created: Wed Nov 15 20:20:49 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_projectManager(object):
    def setupUi(self, projectManager):
        projectManager.setObjectName("projectManager")
        projectManager.resize(528, 480)
        self.centralwidget = QtGui.QWidget(projectManager)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.projName_le = QtGui.QLineEdit(self.groupBox)
        self.projName_le.setObjectName("projName_le")
        self.verticalLayout_2.addWidget(self.projName_le)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.cutomerName_le = QtGui.QLineEdit(self.groupBox)
        self.cutomerName_le.setObjectName("cutomerName_le")
        self.verticalLayout_4.addWidget(self.cutomerName_le)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.deadline_de = QtGui.QDateEdit(self.groupBox)
        self.deadline_de.setCalendarPopup(True)
        self.deadline_de.setObjectName("deadline_de")
        self.verticalLayout_5.addWidget(self.deadline_de)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.projManagerName_le = QtGui.QLineEdit(self.groupBox)
        self.projManagerName_le.setText("")
        self.projManagerName_le.setObjectName("projManagerName_le")
        self.verticalLayout_6.addWidget(self.projManagerName_le)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.projManagerEmail_le = QtGui.QLineEdit(self.groupBox)
        self.projManagerEmail_le.setObjectName("projManagerEmail_le")
        self.verticalLayout_6.addWidget(self.projManagerEmail_le)
        self.info_lb = QtGui.QLabel(self.groupBox)
        self.info_lb.setFrameShape(QtGui.QFrame.StyledPanel)
        self.info_lb.setObjectName("info_lb")
        self.verticalLayout_6.addWidget(self.info_lb)
        self.verticalLayout_6.setStretch(7, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings_btn = QtGui.QPushButton(self.groupBox_2)
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout.addWidget(self.settings_btn)
        self.cleanup_btn = QtGui.QPushButton(self.groupBox_2)
        self.cleanup_btn.setObjectName("cleanup_btn")
        self.horizontalLayout.addWidget(self.cleanup_btn)
        self.arch_btn = QtGui.QPushButton(self.groupBox_2)
        self.arch_btn.setObjectName("arch_btn")
        self.horizontalLayout.addWidget(self.arch_btn)
        self.create_btn = QtGui.QPushButton(self.groupBox_2)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout.addWidget(self.create_btn)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.proj_list = QtGui.QListWidget(self.centralwidget)
        self.proj_list.setObjectName("proj_list")
        self.gridLayout.addWidget(self.proj_list, 0, 1, 1, 1)
        projectManager.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(projectManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        projectManager.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(projectManager)
        self.statusbar.setObjectName("statusbar")
        projectManager.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(projectManager)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtGui.QAction(projectManager)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOptions.addAction(self.actionSettings)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(projectManager)
        QtCore.QMetaObject.connectSlotsByName(projectManager)

    def retranslateUi(self, projectManager):
        projectManager.setWindowTitle(QtGui.QApplication.translate("projectManager", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("projectManager", "Paramters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("projectManager", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("projectManager", "Customer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("projectManager", "Deadline", None, QtGui.QApplication.UnicodeUTF8))
        self.deadline_de.setDisplayFormat(QtGui.QApplication.translate("projectManager", "d/M/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("projectManager", "Project manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("projectManager", "Project Manager email", None, QtGui.QApplication.UnicodeUTF8))
        self.info_lb.setText(QtGui.QApplication.translate("projectManager", "ТЕКСТ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("projectManager", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_btn.setText(QtGui.QApplication.translate("projectManager", "settings", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanup_btn.setText(QtGui.QApplication.translate("projectManager", "cleanup", None, QtGui.QApplication.UnicodeUTF8))
        self.arch_btn.setText(QtGui.QApplication.translate("projectManager", "archive", None, QtGui.QApplication.UnicodeUTF8))
        self.create_btn.setText(QtGui.QApplication.translate("projectManager", "create", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("projectManager", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("projectManager", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("projectManager", "About", None, QtGui.QApplication.UnicodeUTF8))

