# -*- coding: utf-8 -*-

# Form implementation generated from reading uis file 'E:\GoogleDrive\3D\Python\education\09_projManager\homework_projectManager\widgets\settingsDialog.uis'
#
# Created: Tue Nov 14 16:50:36 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(324, 360)
        self.verticalLayout_2 = QtGui.QVBoxLayout(settingsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(settingsDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.projPath_le = QtGui.QLineEdit(self.groupBox)
        self.projPath_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projPath_le.setObjectName("projPath_le")
        self.horizontalLayout.addWidget(self.projPath_le)
        self.projPathDialog_btn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projPathDialog_btn.sizePolicy().hasHeightForWidth())
        self.projPathDialog_btn.setSizePolicy(sizePolicy)
        self.projPathDialog_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.projPathDialog_btn.setObjectName("projPathDialog_btn")
        self.horizontalLayout.addWidget(self.projPathDialog_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.backupPath_le = QtGui.QLineEdit(self.groupBox)
        self.backupPath_le.setObjectName("backupPath_le")
        self.horizontalLayout_2.addWidget(self.backupPath_le)
        self.backUpPathDialog_btn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backUpPathDialog_btn.sizePolicy().hasHeightForWidth())
        self.backUpPathDialog_btn.setSizePolicy(sizePolicy)
        self.backUpPathDialog_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.backUpPathDialog_btn.setObjectName("backUpPathDialog_btn")
        self.horizontalLayout_2.addWidget(self.backUpPathDialog_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_btn = QtGui.QPushButton(settingsDialog)
        self.add_btn.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_btn.sizePolicy().hasHeightForWidth())
        self.add_btn.setSizePolicy(sizePolicy)
        self.add_btn.setMinimumSize(QtCore.QSize(125, 23))
        self.add_btn.setMaximumSize(QtCore.QSize(150, 30))
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.rem_btn = QtGui.QPushButton(settingsDialog)
        self.rem_btn.setMinimumSize(QtCore.QSize(125, 23))
        self.rem_btn.setMaximumSize(QtCore.QSize(150, 30))
        self.rem_btn.setObjectName("rem_btn")
        self.horizontalLayout_3.addWidget(self.rem_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.template_trw = QtGui.QTreeWidget(settingsDialog)
        self.template_trw.setRootIsDecorated(True)
        self.template_trw.setHeaderHidden(True)
        self.template_trw.setObjectName("template_trw")
        self.template_trw.headerItem().setText(0, "1")
        self.template_trw.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.template_trw)
        self.buttonBox = QtGui.QDialogButtonBox(settingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(settingsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), settingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), settingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        settingsDialog.setWindowTitle(QtGui.QApplication.translate("settingsDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("settingsDialog", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("settingsDialog", "path to projects", None, QtGui.QApplication.UnicodeUTF8))
        self.projPathDialog_btn.setText(QtGui.QApplication.translate("settingsDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("settingsDialog", "path for backup", None, QtGui.QApplication.UnicodeUTF8))
        self.backUpPathDialog_btn.setText(QtGui.QApplication.translate("settingsDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.add_btn.setText(QtGui.QApplication.translate("settingsDialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.rem_btn.setText(QtGui.QApplication.translate("settingsDialog", "-", None, QtGui.QApplication.UnicodeUTF8))

