# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\GoogleDrive\3D\Python\education\12_Converter\ImgConverter_homework\converter.ui'
#
# Created: Wed Nov 29 18:53:08 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ImgConverter(object):
    def setupUi(self, ImgConverter):
        ImgConverter.setObjectName("ImgConverter")
        ImgConverter.resize(668, 518)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImgConverter.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(ImgConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtGui.QFormLayout(self.centralwidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.convPath_lb = QtGui.QLabel(self.groupBox)
        self.convPath_lb.setObjectName("convPath_lb")
        self.horizontalLayout.addWidget(self.convPath_lb)
        self.convPath_btn = QtGui.QPushButton(self.groupBox)
        self.convPath_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.convPath_btn.setObjectName("convPath_btn")
        self.horizontalLayout.addWidget(self.convPath_btn)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sourceFiles_ly = QtGui.QHBoxLayout()
        self.sourceFiles_ly.setObjectName("sourceFiles_ly")
        self.horizontalLayout_3.addLayout(self.sourceFiles_ly)
        self.source_ly = QtGui.QVBoxLayout()
        self.source_ly.setObjectName("source_ly")
        self.folder_btn = QtGui.QPushButton(self.groupBox_2)
        self.folder_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.folder_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.folder_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon_folder-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folder_btn.setIcon(icon1)
        self.folder_btn.setObjectName("folder_btn")
        self.source_ly.addWidget(self.folder_btn)
        self.img_btn = QtGui.QPushButton(self.groupBox_2)
        self.img_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.img_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.img_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon_images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.img_btn.setIcon(icon2)
        self.img_btn.setObjectName("img_btn")
        self.source_ly.addWidget(self.img_btn)
        self.delAll_btn = QtGui.QPushButton(self.groupBox_2)
        self.delAll_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.delAll_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.delAll_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon_trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delAll_btn.setIcon(icon3)
        self.delAll_btn.setObjectName("delAll_btn")
        self.source_ly.addWidget(self.delAll_btn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.source_ly.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.source_ly)
        self.horizontalLayout_3.setStretch(0, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.compression_grpb = QtGui.QGroupBox(self.groupBox_2)
        self.compression_grpb.setEnabled(True)
        self.compression_grpb.setObjectName("compression_grpb")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.compression_grpb)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.compression_chb = QtGui.QCheckBox(self.compression_grpb)
        self.compression_chb.setObjectName("compression_chb")
        self.horizontalLayout_2.addWidget(self.compression_chb)
        self.compression_spb = QtGui.QSpinBox(self.compression_grpb)
        self.compression_spb.setEnabled(True)
        self.compression_spb.setMinimum(1)
        self.compression_spb.setMaximum(10)
        self.compression_spb.setProperty("value", 7)
        self.compression_spb.setObjectName("compression_spb")
        self.horizontalLayout_2.addWidget(self.compression_spb)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.compression_grpb)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scaleVal_le = QtGui.QLabel(self.groupBox_4)
        self.scaleVal_le.setObjectName("scaleVal_le")
        self.verticalLayout_2.addWidget(self.scaleVal_le)
        self.scale_sldr = QtGui.QSlider(self.groupBox_4)
        self.scale_sldr.setMaximum(100)
        self.scale_sldr.setSingleStep(1)
        self.scale_sldr.setProperty("value", 100)
        self.scale_sldr.setOrientation(QtCore.Qt.Horizontal)
        self.scale_sldr.setObjectName("scale_sldr")
        self.verticalLayout_2.addWidget(self.scale_sldr)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.groupBox_4)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.outputPath_ly = QtGui.QHBoxLayout()
        self.outputPath_ly.setObjectName("outputPath_ly")
        self.horizontalLayout_5.addLayout(self.outputPath_ly)
        self.outputPath_btn = QtGui.QPushButton(self.groupBox_6)
        self.outputPath_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.outputPath_btn.setObjectName("outputPath_btn")
        self.horizontalLayout_5.addWidget(self.outputPath_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outExt_ly = QtGui.QHBoxLayout()
        self.outExt_ly.setObjectName("outExt_ly")
        self.horizontalLayout_4.addLayout(self.outExt_ly)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_7)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.startStop_btn = QtGui.QPushButton(self.centralwidget)
        self.startStop_btn.setObjectName("startStop_btn")
        self.verticalLayout_6.addWidget(self.startStop_btn)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.SpanningRole, self.verticalLayout_6)
        self.extMan_ly = QtGui.QGroupBox(self.centralwidget)
        self.extMan_ly.setObjectName("extMan_ly")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.extMan_ly)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addExt_le = QtGui.QLineEdit(self.extMan_ly)
        self.addExt_le.setObjectName("addExt_le")
        self.verticalLayout_5.addWidget(self.addExt_le)
        self.extList_ly = QtGui.QVBoxLayout()
        self.extList_ly.setObjectName("extList_ly")
        self.verticalLayout_5.addLayout(self.extList_ly)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectAll_btn = QtGui.QPushButton(self.extMan_ly)
        self.selectAll_btn.setObjectName("selectAll_btn")
        self.horizontalLayout_6.addWidget(self.selectAll_btn)
        self.selectNone_btn = QtGui.QPushButton(self.extMan_ly)
        self.selectNone_btn.setObjectName("selectNone_btn")
        self.horizontalLayout_6.addWidget(self.selectNone_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.setStretch(1, 1)
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.extMan_ly)
        ImgConverter.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImgConverter)
        QtCore.QObject.connect(self.scale_sldr, QtCore.SIGNAL("valueChanged(int)"), self.scaleVal_le.setNum)
        QtCore.QObject.connect(self.compression_chb, QtCore.SIGNAL("clicked(bool)"), self.compression_spb.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ImgConverter)

    def retranslateUi(self, ImgConverter):
        ImgConverter.setWindowTitle(QtGui.QApplication.translate("ImgConverter", "Image Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ImgConverter", "Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.convPath_lb.setText(QtGui.QApplication.translate("ImgConverter", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.convPath_btn.setText(QtGui.QApplication.translate("ImgConverter", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ImgConverter", "Source files", None, QtGui.QApplication.UnicodeUTF8))
        self.compression_grpb.setTitle(QtGui.QApplication.translate("ImgConverter", "jpg compression", None, QtGui.QApplication.UnicodeUTF8))
        self.compression_chb.setText(QtGui.QApplication.translate("ImgConverter", "compress", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ImgConverter", "Resize", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleVal_le.setText(QtGui.QApplication.translate("ImgConverter", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("ImgConverter", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.outputPath_btn.setText(QtGui.QApplication.translate("ImgConverter", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.startStop_btn.setText(QtGui.QApplication.translate("ImgConverter", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.extMan_ly.setTitle(QtGui.QApplication.translate("ImgConverter", "Extensions", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAll_btn.setText(QtGui.QApplication.translate("ImgConverter", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.selectNone_btn.setText(QtGui.QApplication.translate("ImgConverter", "None", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
